trigger:
  - master

strategy:
  matrix:
    linux_node_12:
      imageName: 'ubuntu-latest'
      node_version: 12.x
    mac_node_12:
      imageName: 'macos-10.13'
      node_version: 12.x
    mac_node_13:
      imageName: 'macos-10.13'
      node_version: 13.x

pool:
  vmImage: $(imageName)

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)
    displayName: 'Install Node.js'

  - script: yarn
    displayName: 'install dependencies'

  - script: yarn build
    displayName: 'running build'

  - script: yarn test
    displayName: 'running tests'
